// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEcHqPZkuVz4AuqDbnHEJ7JR-Rz9pbINw',
    appId: '1:736169239223:web:7392c52d97c5ff32e96332',
    messagingSenderId: '736169239223',
    projectId: 'studentacr-4af49',
    authDomain: 'studentacr-4af49.firebaseapp.com',
    storageBucket: 'studentacr-4af49.appspot.com',
    measurementId: 'G-93HN85B2VE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApfPRljfEUDX95zXyUNlyeLotq01KSAjc',
    appId: '1:736169239223:android:02f4b7d1ccdf8f8ce96332',
    messagingSenderId: '736169239223',
    projectId: 'studentacr-4af49',
    storageBucket: 'studentacr-4af49.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADhILNCmn-6rqlD3c1K0dKxFGxFPG2adE',
    appId: '1:736169239223:ios:82920d78c81ffdbde96332',
    messagingSenderId: '736169239223',
    projectId: 'studentacr-4af49',
    storageBucket: 'studentacr-4af49.appspot.com',
    iosClientId: '736169239223-shaqfb9obevohoq1dfrdmsqv27b7rlvl.apps.googleusercontent.com',
    iosBundleId: 'com.example.student',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADhILNCmn-6rqlD3c1K0dKxFGxFPG2adE',
    appId: '1:736169239223:ios:0f7bc071503c1c42e96332',
    messagingSenderId: '736169239223',
    projectId: 'studentacr-4af49',
    storageBucket: 'studentacr-4af49.appspot.com',
    iosClientId: '736169239223-hhpjamt2bsp673b2c9ta0epm2g6fmmcm.apps.googleusercontent.com',
    iosBundleId: 'com.example.student.RunnerTests',
  );
}
